### ISSUE TITLE
JSON.parse Failed to parse json

### ISSUE THREAD

**Issue by onestep749** [fr34kyn01535/discord-fs#2]
This package is broken and does not work.

complete log https://dpaste.com/4BNE3ZMS5.txt

/.git/discord-fs $ cd ..
seeder@isoseeder95 ~/.git $ cd discord-fs/
seeder@isoseeder95 ~/.git/discord-fs $ ls
index.ts  package.json       README.md  tsconfig.json
LICENSE   package-lock.json  src
seeder@isoseeder95 ~/.git/discord-fs $ npm install
npm ERR! code EJSONPARSE
npm ERR! file /home/seeder/.git/discord-fs/package.json
npm ERR! JSON.parse Failed to parse json
npm ERR! JSON.parse Unexpected string in JSON at position 127 while parsing '{
npm ERR! JSON.parse   "name": "discord-storage-ftp",
npm ERR! JSON.parse   "ve'
npm ERR! JSON.parse Failed to parse package.json data.
npm ERR! JSON.parse package.json must be actual JSON, not just JavaScript.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/seeder/.npm/_logs/2020-10-31T19_15_45_117Z-debug.log
[](url)

thanks for that

**Comment by fr34kyn01535** [comment]
Yep, was a pretty stupid typo in package.json, its fixed
