### ISSUE TITLE
Failed at the discord-storage-ftp@1.0.0 start script.

### ISSUE THREAD

**Issue by ghost** [fr34kyn01535/discord-fs#3]
...

**Comment by BluelyTASer** [comment]
I think i have found out the error, it appears another typo relationated for index.ts, by replacing it to index.js, it should fix it, at 10:45 AM EST, I'll test this, if it successfully creates FTP server and connect it, I'll close this.

**Comment by BluelyTASer** [comment]
Never mind... i throws another error, keeping this issue open.
```
> discord-storage-ftp@1.0.0 start /content/discord-fs-master
> node index.js

/content/discord-fs-master/index.js:1
import * as Discord from "discord.js";
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at Module._compile (internal/modules/cjs/loader.js:891:18)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
    at Module.load (internal/modules/cjs/loader.js:811:32)
    at Function.Module._load (internal/modules/cjs/loader.js:723:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1043:10)
    at internal/main/run_main_module.js:17:11
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! discord-storage-ftp@1.0.0 start: `node index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the discord-storage-ftp@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-11-16T16_15_15_517Z-debug.log
```

**Comment by fr34kyn01535** [comment]
Typescript compilation was missing. fixed that

**Comment by BluelyTASer** [comment]
Failed at the fuse-bindings@2.11.2 install script. occurs when using npm install on windows 7/8/10, you need to make sure that fuse is installed on Linux or WSL and use npm install, all listed exports and npm start on Linux or WSL instead.
![405](https://user-images.githubusercontent.com/59511669/101281774-db1f5400-37af-11eb-90b8-de46fc0f6242.PNG)

**Comment by fr34kyn01535** [comment]
You might also just comment fuse out to make it work with the other interfaces.

**Comment by BluelyTASer** [comment]
> You might also just comment fuse out to make it work with the other interfaces.

It turns out that the error keeps appearing when attempting to install fuse_bindings whenever fuse is installed or not. could you fix this?
![407](https://user-images.githubusercontent.com/59511669/101283093-3f91e180-37b7-11eb-95a3-58de51fcda2d.PNG)

**Comment by BluelyTASer** [comment]
> You might also just comment fuse out to make it work with the other interfaces.

After sucessful command with npm install with some of warnings and no errors, another error appears when !npm install, can you fix this?

![408](https://user-images.githubusercontent.com/59511669/101283485-6f41e900-37b9-11eb-8aa5-a76decd79862.PNG)

**Comment by BluelyTASer** [comment]
Also this...

![409](https://user-images.githubusercontent.com/59511669/101283769-576b6480-37bb-11eb-9285-0a88596558f8.PNG)
