### ISSUE TITLE
When they already been set, "GUILD, CHANNEL and TOKEN must be set" appears.

### ISSUE THREAD

**Issue by ghost** [fr34kyn01535/discord-fs#4]
...

**Comment by BluelyTASer** [comment]
I have to replace all desired process.env values into desired values I choosed and it worked, I'll keep running it 24/7 as my proprietary of unlimited cloud storage, and i couldn't solve the FuseBackend error so i left it there, I'll keep this issue open incase that export command doesn't works for you too, also all errors that appeared from start to before GUILD, CHANNEL, and TOKEN must be set! appears on my screen are bypassed by installing packages that you didn't list on your installation guide including npm install typescript and install libfuse-dev that fixes the errors.
![415](https://user-images.githubusercontent.com/59511669/101286956-5131b400-37cc-11eb-8a3c-3b18fb6f3d9d.PNG)

**Comment by BluelyTASer** [comment]
i just had to use ngrok and i was able to make the log appear. closing this one and opening new one.
```
true
OK: 220 Service ready for new user
> AUTH TLS
ERR: 502 Command not supported
> AUTH SSL
ERR: 502 Command not supported
> USER anonymous
OK: 331 User anonymous ok, send password
> PASS anonymous@example.com
OK: 230 User anonymous logged in
> PWD 
OK: 257 "/" is the current directory
> TYPE I
OK: 200 Transfer type set to binary
> PASV 
OK: 227 Entering passive mode (0,0,0,0,166,117)
> LIST 
```
