### ISSUE TITLE
Can't create file/folder in discord-fs using FUSE

### ISSUE THREAD

**Issue by ghost** [fr34kyn01535/discord-fs#6]
...

**Comment by BluelyTASer** [comment]
HTTPFrontend is the only thing that works, FTPFrontend and FuseFrontend are broken...
![447](https://user-images.githubusercontent.com/59511669/101457416-44b87300-3914-11eb-870e-8134b015a386.PNG)

**Comment by BluelyTASer** [comment]
It was been since 108 days that i opened that issue and still no developer's response, is he inactive or what? 🤔
